on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        dc:
          - dmd-latest
          - dmd-2.101.2
          - ldc-latest
          - ldc-1.31.0
        exclude:
          # macOS requires DMD >= 2.107.1
          - os: macOS-latest
            dc: dmd-2.101.2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.dc }}

      - name: Run tests
        shell: bash
        run: |
          dub test --compiler=${DC}
          dub test --compiler=${DC} --build=unittest-dip1000
          if [ "$DC" = "dmd" ]; then ./test-betterc.sh; fi
